[2019-04-30 23:33:11,715] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: bash_xcom_pull_POC.pull_from_bash 2019-05-01T03:32:56.517678+00:00 [queued]>
[2019-04-30 23:33:11,719] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: bash_xcom_pull_POC.pull_from_bash 2019-05-01T03:32:56.517678+00:00 [queued]>
[2019-04-30 23:33:11,720] {__init__.py:1353} INFO - 
--------------------------------------------------------------------------------
[2019-04-30 23:33:11,720] {__init__.py:1354} INFO - Starting attempt 1 of 1
[2019-04-30 23:33:11,720] {__init__.py:1355} INFO - 
--------------------------------------------------------------------------------
[2019-04-30 23:33:11,728] {__init__.py:1374} INFO - Executing <Task(BashOperator): pull_from_bash> on 2019-05-01T03:32:56.517678+00:00
[2019-04-30 23:33:11,728] {base_task_runner.py:119} INFO - Running: ['airflow', 'run', 'bash_xcom_pull_POC', 'pull_from_bash', '2019-05-01T03:32:56.517678+00:00', '--job_id', '271', '--raw', '-sd', 'DAGS_FOLDER/get_xcom_values.py', '--cfg_path', '/tmp/tmp806hobzk']
[2019-04-30 23:33:12,008] {base_task_runner.py:101} INFO - Job 271: Subtask pull_from_bash /home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/configuration.py:214: FutureWarning: The task_runner setting in [core] has the old default value of 'BashTaskRunner'. This value has been changed to 'StandardTaskRunner' in the running config, but please update your config before Apache Airflow 2.0.
[2019-04-30 23:33:12,008] {base_task_runner.py:101} INFO - Job 271: Subtask pull_from_bash   FutureWarning,
[2019-04-30 23:33:12,154] {base_task_runner.py:101} INFO - Job 271: Subtask pull_from_bash [2019-04-30 23:33:12,154] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-04-30 23:33:12,297] {base_task_runner.py:101} INFO - Job 271: Subtask pull_from_bash [2019-04-30 23:33:12,296] {__init__.py:305} INFO - Filling up the DagBag from /home/mjcarleb/HESWork/CSCI-E29/2019sp-airflow_project-mjcarleb/dags/get_xcom_values.py
[2019-04-30 23:33:12,325] {base_task_runner.py:101} INFO - Job 271: Subtask pull_from_bash [2019-04-30 23:33:12,325] {cli.py:517} INFO - Running <TaskInstance: bash_xcom_pull_POC.pull_from_bash 2019-05-01T03:32:56.517678+00:00 [running]> on host localhost.localdomain
[2019-04-30 23:33:12,333] {bash_operator.py:81} INFO - Tmp dir root location: 
 /tmp
[2019-04-30 23:33:12,333] {bash_operator.py:90} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_ID=bash_xcom_pull_POC
AIRFLOW_CTX_TASK_ID=pull_from_bash
AIRFLOW_CTX_EXECUTION_DATE=2019-05-01T03:32:56.517678+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2019-05-01T03:32:56.517678+00:00
[2019-04-30 23:33:12,333] {bash_operator.py:104} INFO - Temporary script location: /tmp/airflowtmp0klr0432/pull_from_bashvwe4sbr9
[2019-04-30 23:33:12,333] {bash_operator.py:114} INFO - Running command: touch $AIRFLOW_HOME/bash.tmp
[2019-04-30 23:33:12,337] {bash_operator.py:123} INFO - Output:
[2019-04-30 23:33:12,338] {bash_operator.py:131} INFO - Command exited with return code 0
[2019-04-30 23:33:12,353] {base_task_runner.py:101} INFO - Job 271: Subtask pull_from_bash /home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/operators/bash_operator.py:70: PendingDeprecationWarning: Invalid arguments were passed to BashOperator (task_id: pull_from_bash). Support for passing such arguments will be dropped in Airflow 2.0. Invalid arguments were:
[2019-04-30 23:33:12,353] {base_task_runner.py:101} INFO - Job 271: Subtask pull_from_bash *args: ()
[2019-04-30 23:33:12,353] {base_task_runner.py:101} INFO - Job 271: Subtask pull_from_bash **kwargs: {'provide_context': True}
[2019-04-30 23:33:12,353] {base_task_runner.py:101} INFO - Job 271: Subtask pull_from_bash   super(BashOperator, self).__init__(*args, **kwargs)
[2019-04-30 23:33:16,719] {logging_mixin.py:95} INFO - [2019-04-30 23:33:16,719] {jobs.py:2562} INFO - Task exited with return code 0
