[2019-04-29 09:12:50,336] {models.py:1359} INFO - Dependencies all met for <TaskInstance: s3_read_yelpADV_files.change_dir 2019-04-28T00:00:00+00:00 [queued]>
[2019-04-29 09:12:50,339] {models.py:1359} INFO - Dependencies all met for <TaskInstance: s3_read_yelpADV_files.change_dir 2019-04-28T00:00:00+00:00 [queued]>
[2019-04-29 09:12:50,339] {models.py:1571} INFO - 
--------------------------------------------------------------------------------
Starting attempt 1 of 2
--------------------------------------------------------------------------------

[2019-04-29 09:12:50,348] {models.py:1593} INFO - Executing <Task(BashOperator): change_dir> on 2019-04-28T00:00:00+00:00
[2019-04-29 09:12:50,348] {base_task_runner.py:118} INFO - Running: ['bash', '-c', 'airflow run s3_read_yelpADV_files change_dir 2019-04-28T00:00:00+00:00 --job_id 113 --raw -sd DAGS_FOLDER/S3_Read_Yelp_into_df.py --cfg_path /tmp/tmp5lasdkcq']
[2019-04-29 09:12:50,821] {base_task_runner.py:101} INFO - Job 113: Subtask change_dir [2019-04-29 09:12:50,820] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-04-29 09:12:50,972] {base_task_runner.py:101} INFO - Job 113: Subtask change_dir [2019-04-29 09:12:50,972] {models.py:273} INFO - Filling up the DagBag from /home/mjcarleb/HESWork/CSCI-E29/2019sp-airflow_project-mjcarleb/dags/S3_Read_Yelp_into_df.py
[2019-04-29 09:12:51,007] {base_task_runner.py:101} INFO - Job 113: Subtask change_dir [2019-04-29 09:12:51,007] {cli.py:520} INFO - Running <TaskInstance: s3_read_yelpADV_files.change_dir 2019-04-28T00:00:00+00:00 [running]> on host localhost.localdomain
[2019-04-29 09:12:51,013] {bash_operator.py:77} INFO - Tmp dir root location: 
 /tmp
[2019-04-29 09:12:51,014] {bash_operator.py:86} INFO - Exporting the following env vars:
AIRFLOW_CTX_EXECUTION_DATE=2019-04-28T00:00:00+00:00
AIRFLOW_CTX_TASK_ID=change_dir
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-28T00:00:00+00:00
AIRFLOW_CTX_DAG_ID=s3_read_yelpADV_files
[2019-04-29 09:12:51,014] {bash_operator.py:100} INFO - Temporary script location: /tmp/airflowtmpdg671ruj/change_dirfsirgr8p
[2019-04-29 09:12:51,014] {bash_operator.py:110} INFO - Running command: cd cd $AIRFLOW_HOME
[2019-04-29 09:12:51,017] {bash_operator.py:119} INFO - Output:
[2019-04-29 09:12:51,018] {bash_operator.py:123} INFO - /tmp/airflowtmpdg671ruj/change_dirfsirgr8p: line 1: cd: cd: No such file or directory
[2019-04-29 09:12:51,018] {bash_operator.py:127} INFO - Command exited with return code 1
[2019-04-29 09:12:51,022] {models.py:1788} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/models.py", line 1657, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/operators/bash_operator.py", line 131, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2019-04-29 09:12:51,023] {models.py:1811} INFO - Marking task as UP_FOR_RETRY
[2019-04-29 09:12:51,033] {base_task_runner.py:101} INFO - Job 113: Subtask change_dir /home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/utils/helpers.py:356: DeprecationWarning: Importing 'BashOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
[2019-04-29 09:12:51,033] {base_task_runner.py:101} INFO - Job 113: Subtask change_dir   DeprecationWarning)
[2019-04-29 09:12:51,034] {base_task_runner.py:101} INFO - Job 113: Subtask change_dir Traceback (most recent call last):
[2019-04-29 09:12:51,034] {base_task_runner.py:101} INFO - Job 113: Subtask change_dir   File "/home/mjcarleb/anaconda3/envs/airflow/bin/airflow", line 32, in <module>
[2019-04-29 09:12:51,034] {base_task_runner.py:101} INFO - Job 113: Subtask change_dir     args.func(args)
[2019-04-29 09:12:51,034] {base_task_runner.py:101} INFO - Job 113: Subtask change_dir   File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-04-29 09:12:51,034] {base_task_runner.py:101} INFO - Job 113: Subtask change_dir     return f(*args, **kwargs)
[2019-04-29 09:12:51,034] {base_task_runner.py:101} INFO - Job 113: Subtask change_dir   File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/bin/cli.py", line 526, in run
[2019-04-29 09:12:51,034] {base_task_runner.py:101} INFO - Job 113: Subtask change_dir     _run(args, dag, ti)
[2019-04-29 09:12:51,034] {base_task_runner.py:101} INFO - Job 113: Subtask change_dir   File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/bin/cli.py", line 445, in _run
[2019-04-29 09:12:51,034] {base_task_runner.py:101} INFO - Job 113: Subtask change_dir     pool=args.pool,
[2019-04-29 09:12:51,034] {base_task_runner.py:101} INFO - Job 113: Subtask change_dir   File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/utils/db.py", line 73, in wrapper
[2019-04-29 09:12:51,034] {base_task_runner.py:101} INFO - Job 113: Subtask change_dir     return func(*args, **kwargs)
[2019-04-29 09:12:51,034] {base_task_runner.py:101} INFO - Job 113: Subtask change_dir   File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/models.py", line 1657, in _run_raw_task
[2019-04-29 09:12:51,034] {base_task_runner.py:101} INFO - Job 113: Subtask change_dir     result = task_copy.execute(context=context)
[2019-04-29 09:12:51,034] {base_task_runner.py:101} INFO - Job 113: Subtask change_dir   File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/operators/bash_operator.py", line 131, in execute
[2019-04-29 09:12:51,034] {base_task_runner.py:101} INFO - Job 113: Subtask change_dir     raise AirflowException("Bash command failed")
[2019-04-29 09:12:51,034] {base_task_runner.py:101} INFO - Job 113: Subtask change_dir airflow.exceptions.AirflowException: Bash command failed
[2019-04-29 09:12:55,347] {logging_mixin.py:95} INFO - [2019-04-29 09:12:55,346] {jobs.py:2527} INFO - Task exited with return code 1
